[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')"
]

[project]
  name = "spade"
  version = "0.1.0"
  dependencies = [
      "agentkit-gf>=0.1.1",
      "pydantic>=2.0.0",
      "cmake-file-api"
  ]